### PR TITLE
WIP: Update to 0.6.8.

### PR DESCRIPTION
**Pull request by ceball**
Also: 
  * requirements/build -> host (conda build 3)
  * update pip command to match current c-f docs.

To do:
  * [ ] re-render when pyct has been updated (this PR depends on https://github.com/conda-forge/pyct-feedstock/pull/2, which depends on https://github.com/conda-forge/staged-recipes/pull/6731).

### CODE REVIEW

**Comment by jbednar** [comment]
Thanks.

**Comment by philippjfr** [comment]
Any idea why this is failing?

```
Error: Failed to render jinja template in /recipe_root/meta.yaml:
'PYTHON' is undefined
```

**Comment by ceball** [comment]
If you're investigating trying to merge this, the main problem is that https://github.com/conda-forge/staged-recipes/pull/6731 has not been merged. It will probably never be merged; my understanding is that pyct should be converted to a single recipe using multiple outputs instead.

**Comment by ceball** [comment]
(Before c-f switched to conda build 3, I'm not sure that would have worked, but it should apparently be fine now. I plan to try it soon. And I probably need to make the same change to geoviews. The 'multiple recipes' approach used in pyct and geoviews is used by other packages too, e.g. dask. There isn't any guidance that I can see about which approach is preferred in general (either with conda, or conda-forge).)

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ceball** [comment]
(I was waiting to re-render, because the build will fail anyway until I deal with pyct.)

**Comment by ocefpaf** [comment]
OK. Let me see what I can do for `pyct`.

Ping @rsignell-usgs who is interested in this recipe.

**Comment by philippjfr** [comment]
Thank you both for getting this merged!

**Pull request merged**
